export const controls = document.getElementById('controls')
export const sounds = document.getElementById('sounds')
export const allSoundButtons = document.querySelectorAll('.music-selector')
export const minutes = document.getElementById('minutes')
export const seconds = document.getElementById('seconds')