export const buttonPressAudio = new Audio('../../assets/sounds/button-press.wav')
export const kitchenTimer = new Audio('../../assets/sounds/kitchen-timer.mp3')
export const forestMusic = new Audio('../../assets/sounds/forest.wav')
forestMusic.loop = true
export const rainMusic = new Audio('../../assets/sounds/rain.wav')
rainMusic.loop = true
export const coffeeShopMusic = new Audio('../../assets/sounds/coffee-shop.wav')
coffeeShopMusic.loop = true
export const fireplaceMusic = new Audio('../../assets/sounds/fireplace.wav')
fireplaceMusic.loop = true